# Generated by Django 4.1.7 on 2023-06-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, help_text='1.admin, 2.normal_user', null=True),
        ),
    ]
