# Generated by Django 4.1.7 on 2023-06-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('child_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.parentmodel')),
            ],
        ),
    ]
