# Generated by Django 4.1.7 on 2023-05-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_user_company_patient_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
