# Generated by Django 4.1.7 on 2023-06-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_parentmodel_childrenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenmodel',
            name='child_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='company_app.parentmodel'),
        ),
    ]
