# Generated by Django 4.1.7 on 2023-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
