# Generated by Django 4.1.7 on 2023-05-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_remove_patient_user_delete_employee_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_availability_duration', models.DurationField()),
            ],
        ),
    ]
