# Generated by Django 4.1.7 on 2023-05-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
