# Generated by Django 4.1.7 on 2023-05-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0008_remove_book_book_availability_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
