# Generated by Django 4.1.7 on 2023-05-17 04:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0010_book'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('author1_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
