# Generated by Django 4.1.7 on 2023-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0011_alter_book_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('upload_user', models.CharField(max_length=200)),
                ('story_expiry', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
