# Generated by Django 4.1.7 on 2023-05-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0012_story_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_expiry',
            new_name='story_uploaded_time',
        ),
    ]
