# Generated by Django 4.1.7 on 2023-05-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0013_rename_story_expiry_story_story_uploaded_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Stories'},
        ),
    ]
