# Generated by Django 4.1.7 on 2023-05-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0014_alter_story_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Storie'},
        ),
    ]
