# Generated by Django 4.1.7 on 2023-06-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0019_cart1_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
