# Generated by Django 4.1.7 on 2023-06-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0020_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAndPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('add_product_permission', models.BooleanField(default=False)),
                ('edit_product_permission', models.BooleanField(default=False)),
                ('mark_product_obselete_permission', models.BooleanField(default=False)),
                ('change_company_info_permission', models.BooleanField(default=False)),
                ('view_order_status_permission', models.BooleanField(default=False)),
                ('buy_products_permission', models.BooleanField(default=False)),
                ('write_reviews_permission', models.BooleanField(default=False)),
                ('change_shipping_address', models.BooleanField(default=False)),
            ],
        ),
    ]
